name: Class Notifications

on:
  schedule:
    # Понедельник
    - cron: '10 8 * * 1'   # 14:10 - 1ч
    - cron: '05 9 * * 1'   # 14:10 - 5мин
    - cron: '05 10 * * 1'  # 15:10 - 5мин
    - cron: '05 13 * * 1'  # 18:10 - 5мин
    - cron: '04 14 * * 1'  # 19:10 - 5мин
    # Вторник
    - cron: '10 10 * * 2'  # 16:10 - 1ч
    - cron: '05 11 * * 2'  # 16:10 - 5мин
    - cron: '05 12 * * 2'  # 17:10 - 5мин
    
    # Среда
    - cron: '10 9 * * 3'   # 15:10 - 1ч
    - cron: '05 10 * * 3'  # 15:10 - 5мин
    - cron: '05 11 * * 3'  # 16:10 - 5мин
    - cron: '05 12 * * 3'  # 17:10 - 5мин
    
    # Четверг
    - cron: '10 6 * * 4'   # 12:10 - 1ч
    - cron: '05 7 * * 4'   # 12:10 - 5мин
    - cron: '05 8 * * 4'   # 13:10 - 5мин
    - cron: '05 9 * * 4'   # 14:10 - 5мин
    - cron: '05 10 * * 4'  # 15:10 - 5мин
    - cron: '05 11 * * 4'  # 16:10 - 5мин
    
    # Пятница
    - cron: '10 11 * * 5'  # 17:10 - 1ч
    - cron: '05 12 * * 5'  # 17:10 - 5мин
    - cron: '05 13 * * 5'  # 18:10 - 5мин
    - cron: '05 14 * * 5'  # 19:10 - 5мин
    
    # Суббота
    - cron: '00 2 * * 6'   # 08:00 - 1ч
    - cron: '55 2 * * 6'   # 08:00 - 5мин
    - cron: '55 3 * * 6'   # 09:00 - 5мин
    - cron: '55 4 * * 6'   # 10:00 - 5мин
    - cron: '05 6 * * 6'   # 11:10 - 5мин
    - cron: '05 9 * * 6'   # 14:10 - 5мин
    - cron: '05 10 * * 6'  # 15:10 - 5мин
  
  workflow_dispatch:  # Для ручного запуска

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run notification worker
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        python main.py
    
    - name: Commit and push data changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update notification data" && git push)
      continue-on-error: true
