name: Telegram Reminder Bot

on:
  # Запуск каждые 5 минут с 06:00 до 22:00 KZT → UTC 01:00–17:59
  schedule:
    - cron: "*/5 1-17 * * *"
  # Запуск при пуше в main
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Устанавливаем Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyTelegramBotAPI

      # 4️⃣ Запускаем бота
      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TZ: Asia/Almaty  # Логирование времени в KZT
        run: |
          echo "Запуск бота: $(date)"
          python main.py
